#!/bin/dash

set -o nounset

VDTWWW=/p/vdt/public/html
TARBALLS_DIR=$VDTWWW/tarball-client
METAPACKAGE=osg-client
INSTALL_ROOT=/p/condor/workspaces/vdt/tarball-client
CA_CERTIFICATES_DIR=/p/condor/workspaces/vdt/osg-ca-certs

Version=
Release=
VR=


main () {
    get_args "${1-}" "${2-}"

    set -o errexit

    die_if_dir_exists $INSTALL_ROOT/$VR

    cd $INSTALL_ROOT
    mkdir -p $VR

    # @sys AFS magic to point to the dir that's appropriate for the system
    ln -s '@sys' $VR/sys

    install_client_tarball i386_rhel5 el5.i386
    install_client_tarball amd64_rhel6 el6.x86_64

    newline
    newline

    if test -e $Version -a ! -L $Version; then
        message "Not creating $Version -> $VR symlink: $Version already exists"
        message "and is not a symlink"
        newline
    else
        ln -snf $VR $Version
    fi

    set +o errexit

    message "Extraction successful. If this was the latest release, please"
    message "update the 'latest' symlink by running:"
    message "\tln -snf $VR $INSTALL_ROOT/latest"
    newline
}

# Sets Version, Release and VR
get_args () {
    if test -z "$1"; then
        die_with_usage
    fi

    Version=$1
    if test -z "$2"; then
        message "Release not specified. Assuming '1' for the release."
        Release=1
    else
        Release=$2
    fi
    VR=${Version}-${Release}
}

install_client_tarball () {
    local sysname
    local dver_arch
    sysname=$1
    dver_arch=$2
    local OLDPWD

    newline
    extract $TARBALLS_DIR/$METAPACKAGE-$VR.$dver_arch.tar.gz $VR/$sysname
    message "Running post-install for $sysname"
    OLDPWD=$PWD
    cd $VR/$sysname
    osg/osg-post-install
    message "Setting up CA certs"
    ./osgrun osg-ca-manage setupCA --url osg
    cd "$OLDPWD"
}


die_with_usage () {
    message "Usage: $0 <VERSION> [<RELEASE>]"
    message " e.g.: $0 3.1.21"
    message "  or   $0 3.1.21 2"
    exit 2
}

die_if_dir_exists () {
    if test -d "$1"; then
        message "$1 already exists. Not overwriting it."
        exit 1
    fi
}

extract () {
    message "Extracting $1 into $2"
    # Note: There is a bug in the version of tar on EL5 that prevents
    # --strip-components from working, hence the explicit 'mv' step
    tar -xzf "$1"
    mv $METAPACKAGE "$2"
}

message () {
    # I can't portably print a tab with echo so I have to use printf
    printf 2>&1 "\t$@\n"
}

newline () { echo 2>&1; }

main "$@"

# vim:ft=sh

