#!/bin/bash

tools=/p/condor/workspaces/vdt/tools

export PATH+=:/p/condor/workspaces/vdt/osg-build

FROM=cndrutil@cs.wisc.edu
REPLYTO=technology-team@opensciencegrid.org
TO=technology-team@opensciencegrid.org

check_for_el () {
  EL=$1
  OSG=$2

  DATE=$(date +%F)
  subject="OSG $OSG packages behind EPEL $EL versions"
  preamble=(OSG $OSG packages out-of-date with respect to EPEL $EL versions,
            as of $DATE:)
  {
  {
  echo "\
From: $FROM
Reply-To: $REPLYTO
To: $TO
MIME-Version: 1.0
Content-Type: text/html
Subject: $subject
"
  "$tools"/osg-outdated-epel-pkgs --html $OSG el$EL --preamble="${preamble[*]}"
  } | hacky_pkg_blacklist | /usr/sbin/sendmail -t
  } </dev/null &>/dev/null &
}

hacky_pkg_blacklist () {
  # Mat doesn't want to hear about koji or mash for osg 3.4
  case $OSG in
    3.4) egrep -vw '(koji|mash)' ;;
     * ) cat ;;
  esac
}

check_for_el 6 3.5
check_for_el 7 3.5
check_for_el 7 devops

