#!/usr/bin/python

# brief summary of open GOC tickets + list of ones open > 30 days

# takes optional Assignee name(s) to list those tickets also

import urllib2
import time
import sys
import re

baseurl = 'https://ticket.grid.iu.edu'
listurl = baseurl + '/list/open'

html = urllib2.urlopen(listurl).read()
html = html.replace('&nbsp;', ' ')
m = re.search(r'<thead>(.*?)</thead>', html, re.S)
hdr = m.group(1)
hdr = re.sub(r'<input.*?/>', '', hdr)
hdrs = re.findall(r'<th>(.*?)</th>', hdr.replace(' ', '_'))
hdridx = dict((h,i) for (i,h) in enumerate(hdrs))

submit = hdridx["Submit_Date"]
owner = hdridx["Assignees"]
title = hdridx["Title"]
ID = hdridx["ID"]

olddate = time.strftime("%F", time.localtime(time.time() - 60*60*24*30))

software = []
old = []

ticket_re = r'''<tr onclick="window.name = 'gocticket_list'(.*?)</tr>'''
ticket_trs = re.findall(ticket_re, html, re.S)

for tr in ticket_trs:
    tds = re.findall(r'<td>(.*?)</td>', tr, re.S)
    if re.search(r'Software Support', tds[owner]):
        software.append(tds)
        if tds[submit] < olddate:
            old.append(tds)

print len(software), "open Software Support ticket(s)"
print
print len(old), "Software Support ticket(s) open for over 30 days"
for tds in old:
    print " - %s [%s/%s] %s" % (tds[submit], baseurl, tds[ID], tds[title])

if sys.argv[1:]:
    pat = '|'.join(sys.argv[1:])
    trs = [tr for tr in software if re.search(pat, tr[owner])]
    print
    print "%d Software Support ticket(s) with Asssignees matching '%s'" % (
        len(trs), pat)
    
    for tds in trs:
        print " - %s [%s/%s] %s" % (tds[submit], baseurl, tds[ID], tds[title])

