#!/usr/bin/python

# Originally written by Carl Edquist; hacked to bits by Tim Cartwright.

import re
import smtplib
import time
import urllib2

FROM = 'Tim Cartwright <cat@cs.wisc.edu>'
RECIPIENTS = (
    'Tim Cartwright <cat@cs.wisc.edu>',
    'Brian Lin <blin@cs.wisc.edu>',
    'Mat Selmeci <matyas+cron@cs.wisc.edu>',
)

HEADERS = ('Open', 'In Progress', 'Ready for Testing', 'Ready for Release')
URL = 'http://opensciencegrid.atlassian.net/projects/SOFTWARE/summary/statistics'

# Adapted from Mat's aggregator/emailer.py script
def mail_message(subject, message, recipients):
    payload = ( 'Subject: %s\r\n' % subject
            +   'From: %s\r\n' % FROM
            +   'To: %s\r\n' % ', '.join(recipients)
            +   '\r\n'
            +   message )
    smtp = smtplib.SMTP('localhost')
    smtp.sendmail(from_addr, recipients, payload)
    smtp.quit()

html = urllib2.urlopen(URL).read()

text = 'JIRA Software tickets:\n\n'
for h in HEADERS:
    m = re.search(r'>%s<.*?<td class="cell-type-collapsed">(\d+)</td>' % h, html, re.S)
    if m:
        text += '    * %s: %s ()\n' % (h, m.groups()[0])
    else:
        text += '    * %s: 0 ()\n' % (h)
text += '\n'
text += 'Completed at %s\n' % (time.strftime('%Y-%m-%d %H:%M'))

subject = 'JIRA ticket summary'
mail_message(subject, text, RECIPIENTS)
