#!/usr/bin/python

import re
import smtplib
import time
from jira.client import JIRA

FROM = 'Tim Cartwright <cat@cs.wisc.edu>'
RECIPIENTS = (
    'Tim Cartwright <cat@cs.wisc.edu>',
    'Brian Lin <blin@cs.wisc.edu>',
    'Mat Selmeci <matyas+cron@cs.wisc.edu>',
)
PROJECT = 'SOFTWARE'
STATUSES = ('Open', 'In Progress', 'Ready for Testing', 'Ready for Release')
URL = 'https://opensciencegrid.atlassian.net'

jira = JIRA(URL)


# Adapted from Mat's aggregator/emailer.py script
def mail_message(subject, message, recipients):
    payload = ( 'Subject: %s\r\n' % subject
            +   'From: %s\r\n' % FROM
            +   'To: %s\r\n' % ', '.join(recipients)
            +   '\r\n'
            +   message )
    smtp = smtplib.SMTP('localhost')
    smtp.sendmail(from_addr, recipients, payload)
    smtp.quit()


def project_status_total(project, status):
    search = 'project = {} AND status = "{}"'.format(project, status)
    return jira.search_issues(search, maxResults=0).total


text = 'JIRA Software tickets:\n\n'
for status in STATUSES:
    count = project_status_total(PROJECT, status)
    text += '    * %s: %s ()\n' % (status, count)
text += '\n'
text += 'Completed at %s\n' % (time.strftime('%Y-%m-%d %H:%M'))

subject = 'JIRA ticket summary'
mail_message(subject, text, RECIPIENTS)
