#!/bin/bash
set -e

usage () {
  echo "usage: $(basename "$0") NVR [arch]  # build NVR + target arch"
  echo "   or: $(basename "$0") NVR.arch    # target binary NVRA"
  echo
  echo "List the packages installed in a koji buildroot for a given build"
  echo "or binary rpm."
  exit
}

[[ $1 = [^-]*-[^-]*-[^-]* ]] || usage
NVR=$1
ARCH=$2

get_1st_nvra () {
  osg-koji buildinfo "$NVR"         |
  sed -n 's/\.rpm$//; /^RPMs:$/,$p' |
  awk -F/ '{print $NF}'             |
  egrep -m1 "\.($1)$"
}

if [[ $ARCH ]]; then
  NVRA=$(get_1st_nvra "$ARCH")
else
  case $NVR in
    *.x86_64 | *.i[3-6]86 | *.noarch | .src ) NVRA=$NVR ;;

    * ) NVRA=$(get_1st_nvra 'noarch|x86_64') ;;
  esac
  ARCH=${NVRA##*.}
fi

case $ARCH in
  x86_64 | i[3-6]86 | noarch | src ) ;;  # OK
  * ) usage ;;
esac

BUILDROOT=$(
  osg-koji rpminfo "$NVRA" |
  awk '$1 == "Buildroot:" {print $2}
           /No such rpm:/ {print >"/dev/stderr"; exit 1}'
)

osg-koji list-buildroot "$BUILDROOT"

