#!/bin/bash

# Display all the usernames of SVN committers of a path, sorted by number of
# commits.

set -eu
set -o pipefail

path_to_check=${1?"Usage: $0 <path to check>"}

# svn log -q gives us output like:
# ------------------------------------------------------------------------
# r22629 | matyas | 2016-03-09 11:12:40 -0600 (Wed, 09 Mar 2016)
# ------------------------------------------------------------------------

# Filter out the lines with data on them, then get the usernames.
# Get a count of each unique username, and sort again, numerically (-n),
# reversed (-r).

svn log -q --use-merge-history "$path_to_check" |
    fgrep ' | ' |
    awk -F' \\| ' '{print $2}' |
    sort |
    uniq -c |
    sort -nr
