#!/bin/bash

usage () {
  echo "$(basename "$0") [3.1|[3.2]] [el5|[el6]]" \
                        "[development|testing|[release]]"
  exit
}

SERIES=${SERIES:-3.2}
EL=${EL:-6}
TAG=${TAG:-release}

while [[ $1 ]]; do
case $1 in
  el[5-9]                     ) EL=${1#el} ;;
  [3-9].[0-9]                 ) SERIES=$1 ;;
  development|testing|release ) TAG=$1 ;;
  *                           ) usage ;;
esac
shift
done

baseurl=http://dl.fedoraproject.org/pub/epel/$EL/SRPMS/

list_epel () {
  wget -qO- "$baseurl" \
  | perl -lne 'print $1 if /<a href="([^"]+)(-[^-"]+){2}"/'
}

list_osg () {
  osg-koji list-tagged --latest --rpms "osg-$SERIES-el$EL-$TAG" \
  | grep '\.src$' | perl -lpe 's/(-[^-]+){2}$//'
}

# print intersection
fgrep -xf <(list_epel) <(list_osg) | sort

