#!/usr/bin/python

import os
import re
import sys
import json
import getopt
import getpass
import urllib2
import operator
import subprocess

def usage(msg=None):
    if msg:
        print >>sys.stderr, msg + "\n"

    s = os.path.basename(__file__)
    print """\
usage: [PASS=...] %s [-u USER[:PASS]] [-d passfd] [-H] COMMAND [args...]

COMMANDs:

  (*)   list-mine
        list-user        USER
        list-org         ORG
        dump-user        USER
        dump-org         ORG
        list-branches    OWNER REPO
        list-tags        OWNER REPO
        list-refs        OWNER REPO
  (*)   create-mine      REPO
  (*)   create-org       ORG   REPO
  (*)   fork-from        OWNER REPO
  (*)   delete           OWNER REPO
  (*)   rename           OWNER REPO NEWNAME
  (*)   set-description  OWNER REPO DESCRIPTION
  (*)   protect-branch   OWNER REPO BRANCH
  (*)   unprotect-branch OWNER REPO BRANCH
        list-prs         OWNER REPO
  (*)   request-pull     OWNER REPO[:BRANCH] [USER:]BRANCH TITLE BODY
  (*)   merge-pr         OWNER REPO NUMBER
  (*)   close-pr         OWNER REPO NUMBER
        
(*) USER login required

PASS for USER is taken from the first of:
  1. -u USER:PASS
  2. -d passfd (read from fd)
  3. read from $PASS env var
  4. read from terminal

Options:
  -H   show http response headers
  -F field[:field...] display fields for repos instead of just "html_url"
     (valid fields are clone_url git_url html_url ssh_url full_name name)
""" % s
    sys.exit()

apiurl = 'https://api.github.com'

GET    = 'GET'
PUT    = 'PUT'
POST   = 'POST'
PATCH  = 'PATCH'
DELETE = 'DELETE'

VALID_FIELDS = set('clone_url git_url html_url ssh_url full_name name'.split())

class Options:
    authstr = None
    show_headers = False
    listfields = ['html_url']

options = Options()

def add_gh_preview_header(req):
    req.add_header("Accept", "application/vnd.github.loki-preview+json")

def add_auth_header(req):
    if options.authstr:
        req.add_header("Authorization", "Basic %s" % options.authstr)

def authsetup(user, passwd):
    from base64 import encodestring
    options.authstr = encodestring('%s:%s' % (user,passwd)).replace('\n', '')

def getpw(user, passfd=None):
    if ':' in user:
        user, pw = user.split(':', 1)
    elif passfd is not None:
        pw = os.fdopen(passfd).readline().rstrip('\n')
    elif 'PASS' in os.environ:
        pw = os.environ['PASS']
    else:
        pw = getpass.getpass('passwd for user %s: ' % user)
    return user, pw

def linkparse(linktext):
    mm = re.findall(r'<([^>]+)>;\s*rel="([^"]+)"', linktext)
    return dict((page, rel) for rel,page in mm)

def get_nextlink(resp):
    linktext = resp.headers.getheader('link')
    if linktext:
        links = linkparse(linktext)
        if 'next' in links:
            return links['next']

def _snarfer(method, url, data=None):
    req = urllib2.Request(url, data)
    add_auth_header(req)
    add_gh_preview_header(req)
    req.get_method = lambda : method
    resp = urllib2.urlopen(req)
    if options.show_headers:
        print "Headers for <%s>" % url
        print "---"
        print resp.headers
    nextlink = get_nextlink(resp)
    return resp.read(), nextlink

def snarfergen(method, url, data=None):
    while url:
        text, url = _snarfer(method, url, data)
        if text:
            j = json.loads(text)
            if type(j) is dict:
                pmsg(j)
            yield j
    
def snarfer(method, path, data=None):
    if data:
        data = json.dumps(data)
    url = apiurl + path
    outs = list(snarfergen(method, url, data))
    nresp = len(outs)
    if nresp == 0:
        return None
    elif nresp == 1:
        return outs[0]
    elif type(outs[0]) is list:
        return reduce(operator.add, outs)
    else:
        return outs

"""
github API notes:

: list-mine      GET /user/repos
: list-user      GET /users/:username/repos
: list-org       GET /orgs/:org/repos
: list-branches  GET /repos/:owner/:repo/branches
: list-tags      GET /repos/:owner/:repo/tags
: list-refs      GET /repos/:owner/:repo/git/refs  # aka git_refs_url
: create-mine    POST /user/repos      {"name": "Repo-Name"}
: create-org     POST /orgs/:org/repos {"name": "Repo-Name"}
: delete         DELETE /repos/:owner/:repo
: rename (edit)  PATCH /repos/:owner/:repo  {"name": "New-Repo-Name"}
: protect-branch PATCH /repos/:owner/:repo/branches/:branch {"enabled": "true"}
: request-pull   POST /repos/:owner/:repo/pulls {
                      "title": "New Feature", "body": "PR description",
                      "base": "master", "head": "someuser:somebranch"}
: merge-pr       PUT /repos/:owner/:repo/pulls/:number/merge
                 # {"commit_title": "title", "commit_message": "desc"}
: close-pr       PATCH /repos/:owner/:repo/pulls/:number {"state": "closed"}
: list-prs       GET /repos/:owner/:repo/pulls
"""

def print_names(seq):
    m = max( len(x['name']) for x in seq )
    for x in seq:
        print "%-*s  %s" % (m, x['name'], x['html_url'])

def print_fields(seq):
    rows = sorted( [ x[f] for f in options.listfields ] for x in seq )
    for row in rows:
        print '\t'.join(row)

def print_fields_sortby(seq, fields, sortby):
    rows = sorted( [x[sortby]] + [ x[f] for f in fields ] for x in seq )
    for row in rows:
        print '\t'.join(row[1:])

def print_refs(seq):
    for x in seq:
        print x["commit"]["sha"], x["name"]

def print_git_refs(seq):
    for x in seq:
        print x["object"]["sha"], x["ref"]

def dump_infos(seq):
    for x in seq:
        print x['html_url']
        w = max(len(xx) for xx in x)
        for xk,xv in sorted(x.items()):
            print "  - %*s: %s" % (w,xk,xv)
        print

def pmsg(j):
    if j and 'message' in j:
        print j['message']

def list_mine():
    print_fields(snarfer(GET, '/user/repos'))

def list_user(username):
    print_fields(snarfer(GET, '/users/%s/repos' % username))

def list_prs(owner, repo):
    print_fields_sortby(snarfer(GET, '/repos/%s/%s/pulls' % (owner, repo)),
            ['html_url', 'title'], 'number')

def list_org(org):
    print_fields(snarfer(GET, '/orgs/%s/repos' % org))

def list_branches(owner, repo):
    print_refs(snarfer(GET, '/repos/%s/%s/branches' % (owner,repo)))

def list_tags(owner, repo):
    print_refs(snarfer(GET, '/repos/%s/%s/tags' % (owner,repo)))

def list_git_refs(owner, repo):
    print_git_refs(snarfer(GET, '/repos/%s/%s/git/refs' % (owner,repo)))

def dump_user(username):
    dump_infos(snarfer(GET, '/users/%s/repos' % username))

def dump_org(org):
    dump_infos(snarfer(GET, '/orgs/%s/repos' % org))

def create_mine(repo):
    snarfer(POST, '/user/repos', {"name": repo})

def create_org(org, repo):
    snarfer(POST, '/orgs/%s/repos' % org, {"name": repo})

def fork_mine(owner, repo):
    snarfer(POST, '/repos/%s/%s/forks' % (owner,repo))

def delete_repo(owner, repo):
    snarfer(DELETE, '/repos/%s/%s' % (owner,repo))

def rename_repo(owner, repo, newname):
    snarfer(PATCH, '/repos/%s/%s' % (owner,repo), {"name": newname})

def set_description(owner, repo, desc):
    snarfer(PATCH, '/repos/%s/%s' % (owner,repo),
           {"name": repo, "description": desc})

def protect_branch(owner, repo, branch):
    snarfer(PATCH, '/repos/%s/%s/branches/%s' % (owner,repo,branch),
           { "protection": {
               "enabled": True,
               "required_status_checks": {
                   "enforcement_level": "everyone",  # or "non_admins", or "off"
                   "contexts": []  # eg, "continuous-integration/travis-ci"
               }
             }
           })

def unprotect_branch(owner, repo, branch):
    snarfer(PATCH, '/repos/%s/%s/branches/%s' % (owner,repo,branch),
           {"protection": {"enabled": False}})

def merge_pr(owner, repo, number):
    snarfer(PUT, "/repos/%s/%s/pulls/%s/merge" % (owner, repo, number))

def close_pr(owner, repo, number):
    snarfer(PATCH, "/repos/%s/%s/pulls/%s" % (owner, repo, number),
           {"state": "closed"})

def request_pull(owner, baserepo, frombranch, title, body):
    if ':' in baserepo:
        repo, basebranch = baserepo.split(':')
    else:
        repo, basebranch = baserepo, "master"

    if ':' in frombranch:
        head = frombranch
    else:
        head = "%s:%s" % (login_user, frombranch)

    print_fields([snarfer(POST, '/repos/%s/%s/pulls' % (owner,repo),
           {"title": title, "body": body, "head": head, "base": basebranch})])

methods = {
#   'command-name':     [method,   user_required],
    'list-mine':        [list_mine,        True],
    'list-user':        [list_user,        False],
    'list-org':         [list_org,         False],
    'dump-user':        [dump_user,        False],
    'dump-org':         [dump_org,         False],
    'list-branches':    [list_branches,    False],
    'list-tags':        [list_tags,        False],
    'list-refs':        [list_git_refs,    False],
    'create-mine':      [create_mine,      True],
    'create-org':       [create_org,       True],
    'fork-from':        [fork_mine,        True],
    'delete':           [delete_repo,      True],
    'rename':           [rename_repo,      True],
    'set-description':  [set_description,  True],
    'protect-branch':   [protect_branch,   True],
    'unprotect-branch': [unprotect_branch, True],
    'request-pull':     [request_pull,     True],
    'list-prs':         [list_prs,         False],
    'merge-pr':         [merge_pr,         True],
    'close-pr':         [close_pr,         True]
}

def checkfields(f):
    if not f:
        usage()
    fields = f.split(':')
    if not all( x in VALID_FIELDS for x in fields ):
        usage()
    return fields

def method_argcount_ok(method, args):
    cmd_args = method.__code__.co_argcount
    def_args = len(method.__defaults__ or [])
    return cmd_args - def_args <= len(args) <= cmd_args

def main(args):
    ops, args = getopt.getopt(args, 'u:d:HF:')
    ops = dict(ops)
    if len(args) < 1:
        usage()

    user   = None
    passfd = None

    if '-u' in ops: user   =     ops['-u']
    if '-d' in ops: passfd = int(ops['-d'])
    if '-H' in ops: options.show_headers = True
    if '-F' in ops: options.listfields = checkfields(ops['-F'])

    command = args[0]
    args = args[1:]

    if command not in methods:
        usage("unrecognized command: '%s'" % command)

    method, user_required = methods[command]

    if not method_argcount_ok(method, args):
        usage("wrong number of args for %s command" % command)

    if user:
        user, passwd = getpw(user, passfd)
        authsetup(user, passwd)
        global login_user
        login_user = user
    elif user_required:
        usage("USER required for %s command" % command)

    method(*args)

if __name__ == '__main__':
    try:
        main(sys.argv[1:])
    except urllib2.HTTPError as e:
        print >>sys.stderr, e
        sys.exit(1)

