#!/bin/sh

# Simple 'watchdog' script for GitHub AFS backups:
# Sends an email containing, for each repo:
# - the last successful fetch time
# - whether a NO_FETCH file is present

rootdir=/p/condor/workspaces/vdt/git
repodir=${rootdir}/repo

email_from=`whoami`@cs.wisc.edu
email_to="matyas+cron@cs.wisc.edu edquist@cs.wisc.edu"

subject="GitHub AFS backups watchdog"

pretty_mtime() {
    # Pretty-print the mtime of a file
    date --date=@`stat --format %Y "$1"`
}

cd $repodir

fmtstr='%-30s %-32s %s\n'

# Build the body of the email
{
    printf "$fmtstr" "Repo directory" "Last successful fetch" "NO_FETCH file"
    printf "$fmtstr" "--------------" "---------------------" "-------------"

    for repo in ./*.git; do
        repo_directory=`basename $repo`

        if [ -f $repo/last-success-mtime ]; then
            last_successful_fetch=`pretty_mtime $repo/last-success-mtime`
        else
            last_successful_fetch="UNKNOWN"
        fi

        if [ -f $repo/NO_FETCH ]; then
            no_fetch_file=YES
        else
            no_fetch_file=''
        fi

        printf "$fmtstr" "$repo_directory" "$last_successful_fetch" "$no_fetch_file"
    done
} | mailx -s "$subject" -r "$email_from" $email_to
