#!/usr/bin/env python

# Requires Python 2.6+

DRYRUN = False

REMOTE_LOGIN            = 'osgsoftware'
REMOTE_HOST             = 'backup.grid.iu.edu'
REMOTE_BASE_PATH        = '/usr/local/backup/osgsoftware'
LOCAL_BACKUP_ROOT       = '/export/backup'
KOJIHOST                = 'koji.chtc.wisc.edu'
DBHOST                  = 'db-01.batlab.org'
RETRIES                 = 10
RETRY_WAIT              = 60
NOTIFY_EMAILS           = [x + '@cs.wisc.edu' for x in ['blin', 'cat', 'edquist', 'matyas+cron', 'tim']]
KEY                     = '/root/osg_backup_key'

DEDUPE_SCRIPT           = "%s/dedupe" % REMOTE_BASE_PATH
REMOTE_LOGIN_HOST       = "%s@%s" % (REMOTE_LOGIN, REMOTE_HOST)

MAIL_DELIVERY_METHOD    = 'sendmail'  # either 'sendmail' or 'smtp'

import glob
import re
import os
import shutil
from subprocess import Popen, PIPE, STDOUT
import sys
import tempfile
import time

import socket
from email.mime.text import MIMEText


class Error(Exception): pass
class CommandError(Error):
    def __init__(self, command, returncode, outerr):
        Error.__init__(self, "Command %r failed with returncode %d, output:\n%s" % (command, returncode, outerr))
        self.command = command
        self.returncode = returncode
        self.outerr = outerr


def compose_message(subject, text, recipients):
    if not isinstance(recipients, str):
        recipients = ', '.join(recipients)

    message = MIMEText(text)
    message['Subject'] = subject
    message['From'] = 'Offsite backup script <%s@%s>' % (os.getlogin(), socket.getfqdn())
    message['To'] = recipients

    return message


def send_message_smtp(message):
    import smtplib
    try:
        smtp = smtplib.SMTP('localhost')
        smtp.sendmail(message['From'], message['To'].split(', '), message.as_string())
        smtp.quit()
        return
    except smtplib.SMTPException, e:
        return str(e)


def send_message_sendmail(message):
    try:
        proc = Popen(['/usr/sbin/sendmail', '-oi', '-t'], stdin=PIPE, stdout=PIPE, stderr=STDOUT)
        outerr = proc.communicate(message.as_string())[0]
        ret = proc.returncode
        if ret != 0:
            return "exit %d from sendmail\noutput:\n%s" % (ret, outerr)
        return
    except OSError, e:
        return str(e)


def send_message(message):
    fail_reason = None
    if MAIL_DELIVERY_METHOD == 'smtp':
        fail_reason = send_message_smtp(message)
    elif MAIL_DELIVERY_METHOD == 'sendmail':
        fail_reason = send_message_sendmail(message)
    else:
        fail_reason = "Invalid MAIL_DELIVERY_METHOD %s" % MAIL_DELIVERY_METHOD

    if fail_reason is not None:
        print "Unable to send email message: %s" % fail_reason
        print "Message text:\n%s" % text


def notify_email(subject, text):
    send_message(compose_message(subject, text, NOTIFY_EMAILS))


def sbacktick(*args, **kwargs):
    # simplified version of utils.sbacktick from osgbuild
    sp_kwargs = kwargs.copy()
    sp_kwargs['stdout'] = PIPE
    sp_kwargs['stderr'] = STDOUT

    if DRYRUN:
        print str(args)
        return 0, ''

    proc = Popen(*args, **sp_kwargs)
    outerr = proc.communicate()[0]

    return proc.returncode, outerr


def csbacktick(*args, **kwargs):
    # checked version of sbacktick
    ret, outerr = sbacktick(*args, **kwargs)
    if ret != 0:
        raise CommandError(command=args[0], returncode=ret, outerr=outerr)
    return outerr


def remote_run_command(commandstr):
    return sbacktick(['ssh', '-i', KEY, REMOTE_LOGIN_HOST, commandstr])


def remote_run_script(script):
    if isinstance(script, list) or isinstance(script, tuple):
        script = "\n".join(script)

    if DRYRUN:
        print "---\n%s\n---" % script
        return 0, ''

    proc = Popen(['ssh', '-i', KEY, REMOTE_LOGIN_HOST, '/bin/bash -s'], stdin=PIPE, stdout=PIPE, stderr=STDOUT)
    outerr = proc.communicate(script)[0]

    return proc.returncode, outerr


def rsync_with_retry(src_path, remote_path, link=None):
    rsync_opts = ['--recursive', '--compress', '--quiet', '--rsh=ssh -i %(KEY)s' % globals()]

    if link:
        rsync_opts.append('--link-dest=%s' % os.path.relpath(link, remote_path))

    dest_path = "%s:%s" % (REMOTE_LOGIN_HOST, remote_path)
    count = 0
    while True:
        try:
            csbacktick(['rsync'] + rsync_opts + [src_path + '/', dest_path])
            return
        except CommandError, e:
            if count >= RETRIES:
                raise
            count += 1
            time.sleep(RETRY_WAIT)


def dedupe(pattern, substitution, from_dirs, logfile=None):
    if isinstance(from_dirs, str):
        from_dirs = [from_dirs]

    script = ['cd  %s' % REMOTE_BASE_PATH]
    for from_dir in from_dirs:
        line = "%s  %s  %s  %s" % (DEDUPE_SCRIPT, re.escape(pattern), re.escape(substitution), re.escape(from_dir))
        if logfile:
            line += "  >> %s  2>&1" % re.escape(logfile)
        script.append(line)

    return remote_run_script(script)


def backup_configs_roothome_and_database(workdir, remote_path):
    for tarball, directory in \
        [('etc.tar.gz'          , os.path.join(KOJIHOST , 'rootfs/etc')),
         ('roothome.tar.gz'     , os.path.join(KOJIHOST , 'rootfs/root')),
         ('pgsql.tar.gz'        , os.path.join(DBHOST   , 'rootfs/var/lib/pgsql')),
         ('pgsql-backup.tar.gz' , os.path.join(DBHOST   , 'rootfs/var/lib/pgsql-backup'))]:

        csbacktick(['tar', '-czpf', os.path.join(workdir, tarball), directory])
    rsync_with_retry(workdir, remote_path)


def backup_packages_with_dedupe(remote_path, remote_link_path, dedupe_pattern, dedupe_substitution, dedupe_logfile):
    packages_dir = os.path.join(KOJIHOST, 'kojifs/packages')
    if not os.path.isdir(packages_dir):
        raise Error(packages_dir + ' is not a directory')

    remote_run_command('mkdir -p  %s' % re.escape(os.path.join(remote_path, 'packages')))

    for package in os.listdir(packages_dir):
        package_dir = os.path.join(packages_dir, package)
        remote_package_dir = os.path.join(remote_path, 'packages', package)
        remote_link_dir = None
        if remote_link_path:
            remote_link_dir = os.path.join(remote_link_path, 'packages', package)

        rsync_with_retry(package_dir, remote_package_dir, link=remote_link_dir)

        if dedupe_pattern and dedupe_substitution:
            dedupe(pattern=dedupe_pattern, substitution=dedupe_substitution, from_dirs=[remote_package_dir], logfile=dedupe_logfile)


def get_backup_statistics(remote_path):
    esc_remote_path = re.escape(remote_path)
    try:
        file_count = int(remote_run_command('find %s -type f | wc -l' % esc_remote_path)[1])
        deduped_count = int(remote_run_command('find %s -type f -links +1 | wc -l' % esc_remote_path)[1])
        disk_usage = remote_run_command('du -hs %s | awk "{print \\$1}"' % esc_remote_path)[1].strip()
        disk_free = remote_run_command('df -h %s' % esc_remote_path)[1].strip()
        return '''\
Files backed up:    %(file_count)7d
Files deduplicated: %(deduped_count)7d
Disk usage:         %(disk_usage)7s
Disk free:
%(disk_free)s
''' % locals()
    except (OSError, ValueError, AttributeError):
        return None


def get_previous_remote_backup_date(current_backup_date):
    """Return the most recent backup date on the remote side that is older than
    current_backup_date"""

    # return dirs in reverse sorted order
    # dates are in YYYY-mm-dd format so they sort
    ret, backup_dirs = remote_run_command('cd "%s" && ls -dr 20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]/' % REMOTE_BASE_PATH)
    if ret != 0:
        return None

    backup_dirs = backup_dirs.strip()
    backup_dates = [x.rstrip('/') for x in backup_dirs.split('\n') if x]
    for date in backup_dates:
        if date < current_backup_date:
            return date
    else:
        return None


def get_current_backup_date():
    """Return the most recent completed backup date"""

    ret, backup_dirs = sbacktick('cd "%s" && ls -dr 20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]/' % LOCAL_BACKUP_ROOT, shell=True)

    if ret != 0:
        return None

    backup_dirs = backup_dirs.strip()
    backup_dates = [x.rstrip('/') for x in backup_dirs.split('\n') if x]

    # Look for rsync processes owned by root. These are likely to be processes
    # doing the original backups. False positives aren't a big deal.
    ret, _ = sbacktick(["pgrep", "-x", "-u", "root", "rsync"])
    try:
        if ret == 0:
            # rsync still running; most recent is assumed to be incomplete
            return backup_dates[1]
        else:
            # no rsync; most recent is assumed to be complete
            return backup_dates[0]
    except IndexError:
        raise Error("No complete backups found")


def main(argv):
    try:
        if remote_run_command('[[ -x %s ]]' % DEDUPE_SCRIPT)[0] != 0:
            raise Error('dedupe script missing from remote side')

        backup_date = get_current_backup_date()
        last_backup_date = get_previous_remote_backup_date(backup_date)

        tempdir = tempfile.mkdtemp(prefix='osg-koji-backup')
        try:

            workdir = os.path.join(tempdir, backup_date)
            yesterdays_backups = os.path.join(LOCAL_BACKUP_ROOT, backup_date)
            remote_path = os.path.join(REMOTE_BASE_PATH, backup_date)
            remote_link_path = None
            if last_backup_date:
                remote_link_path = os.path.join(REMOTE_BASE_PATH, last_backup_date)

            os.makedirs(workdir)

            olddir = os.getcwd()
            os.chdir(yesterdays_backups)

            backup_configs_roothome_and_database(workdir, remote_path)

            logfile = os.path.join(REMOTE_BASE_PATH, 'dedupe-%s.log' % backup_date)
            remote_run_command('rm -f  %s' % re.escape(logfile))
            backup_packages_with_dedupe(remote_path, remote_link_path, backup_date, last_backup_date, logfile)

            os.chdir(olddir)

        finally:
            shutil.rmtree(tempdir)

    except Error, e:
        notify_email('OSG Koji offsite backups failed', str(e))
        return str(e)

    except Exception, e:
        notify_email('OSG Koji offsite backups died', str(e))
        raise

    else:
        message = 'OSG Koji offsite backups to %s succeeded\n' % remote_path
        statistics = get_backup_statistics(remote_path)

        if statistics is not None:
            message += statistics
        else:
            message += 'Unable to get backup statistics\n'

        notify_email('OSG Koji offsite backups completed', message)
        return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))

